---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: memcached
spec:
  values:
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
