---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - path: backend-values.yaml
    target:
      kind: Deployment
      name: ciso-assistant-backend
