---
apiVersion: v1
kind: Service
metadata:
  name: ciso-assistant-backend
spec:
  selector:
    app.kubernetes.io/name: ciso-assistant
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: test
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
